// export const dataDB = [
//     {
//         id: 1,
//         name: "Algo raro",
//         urlImages: "./images/algoRaro.png",
//         stock: 5,
//         price: 1000,
//     },
//     {
//         id: 2,
//         name: "Comida sana",
//         urlImages: "./images/comidaSana.png",
//         stock: 6,
//         price: 2000,
//     },
//     {
//         id: 3,
//         name: "Ensalada",
//         urlImages: "./images/ensalada.png",
//         stock: 7,
//         price: 3000,
//     },
//     {
//         id: 4,
//         name: "Hamburguesa",
//         urlImages: "./images/hambur.png",
//         stock: 8,
//         price: 4000,
//     },
//     {
//         id: 5,
//         name: "Perrito",
//         urlImages: "./images/perrito.png",
//         stock: 9,
//         price: 5000,
//     },
//     {
//         id: 6,
//         name: "Pescado",
//         urlImages: "./images/pez.png",
//         stock: 10,
//         price: 6000,
//     },
//     {
//         id: 7,
//         name: "Pizza",
//         urlImages: "./images/pizza.png",
//         stock: 11,
//         price: 7000,
//     },
//     {
//         id: 8,
//         name: "Ramen",
//         urlImages: "./images/ramen.png",
//         stock: 12,
//         price: 8000,
//     },
//     {
//         id: 9,
//         name: "Taco",
//         urlImages: "./images/taco.png",
//         stock: 13,
//         price: 9000,
//     },
// ];

export const dataDB = [
    {
        id: 1,
        name: "El nombre de la rosa",
        autor:"Umberto Eco",
        category:"Ficcion literaria",
        year:2003,
        pages: 284,
        urlImages: "./books/1_book.webp",
        stock: 5,
        price: 85,
    },
    {
        id: 2,
        name: 'El inversor inteligente',
        autor: 'Benjamin Graham',
        category:"Economia",
        year:2019,
        pages: 624,
        urlImages: "./books/2_book.webp",
        stock: 8,
        price: 81,
    },
    {
        id: 3,
        name: 'La cancion de aquiles',
        autor: 'Madeline Miller',
        category:"Ficcion Moderna",
        year:2011,
        pages: 394,
        urlImages: "./books/3_book.webp",
        stock: 9,
        price: 95,
    },
    {
        id: 4,
        name:'Pizarro, el rey de la baraja',
        autor:'Alan Garcia',
        category:'Ensayo',
        year:2022,
        pages:168,
        urlImages: "./books/4_book.webp",
        stock: 12,
        price:58,
    },
    {
        id: 5,
        name:'Ley de lobos',
        autor:'Leigh Bardugo',
        category:'Ficcion Juvenil',
        year:2021,
        pages: 640,
        urlImages: "./books/5_book.webp",
        stock: 6,
        price:48
    },
    {
        id: 6,
        name:'Sobrenatural',
        autor:'Joe Dispenza',
        category:'Espiritualismo',
        year:2018,
        pages: 408,
        urlImages: "./books/6_book.webp",
        stock: 11,
        price:63,
    },
    {
        id: 7,
        name:'Meditaciones',
        autor:'Marco Aurelio',
        category:'Filosofia',
        year:2021,
        pages: 192,
        urlImages: "./books/7_book.webp",
        stock: 8,
        price: 44
    },
    {
        id: 8,
        name:'El libro de los espiritus',
        autor:'Allan Kardec',
        category:'Espiritualismo',
        year:2009,
        pages: 536,
        urlImages: "./books/8_book.webp",
        stock: 4,
        price:85
    },
    {
        id: 9,
        name:'Homo Deus',
        autor:'Yuval Noah Harari',
        category:'Historia',
        year:2016,
        pages: 489,
        urlImages: "./books/9_book.webp",
        stock: 9,
        price: 88
    },
    {
        id: 10,
        name:'El futuro de la humanidad',
        autor:'Michio Kaku',
        category:'Ciencia',
        year:2019,
        pages:407,
        urlImages: "./books/10_book.webp",
        stock: 11,
        price:83 ,
    },
    {
        id: 11,
        name:'MBA Personal',
        autor:'Josh Kaufman',
        category:'Economia',
        year:2021,
        pages:504,
        urlImages: "./books/11_book.webp",
        stock: 3,
        price: 89,
    },
    {
        id: 12,
        name:'Carta de una desconocida',
        autor:'Stefan Zweig',
        category:'Ficcion',
        year:2021,
        pages:112,
        urlImages: "./books/12_book.webp",
        stock: 7,
        price:109,
    }
    
];
